### ISSUE TITLE
Cannot run the example from the documentation

### ISSUE THREAD

**Issue by sheevy** [MilesCranmer/SymbolicRegression.jl#1]
Hi, I tried to run the example from the documentation but it always fails for me (on both on Windows and Linux and on Julia 1.5.3 and 1.6-beta1).
On freshly installed Julia I run the following (output of most of the commands omitted):
```
(@v1.6) pkg> generate Test2
(@v1.6) pkg> activate Test2
julia> using Pkg
julia> Pkg.add(url="https://github.com/MilesCranmer/SymbolicRegression.jl.git")
julia> using Distributed
julia> addprocs(4)
julia> @everywhere using SymbolicRegression
ERROR: On worker 2:
ArgumentError: Package SymbolicRegression [8254be44-1295-4e6a-a16d-46603ac705cb] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require
   @ .\loading.jl:986
 [2] require
   @ .\loading.jl:910
 [3] #1
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\Distributed.jl:79
 [4] #103
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:274
 [5] run_work_thunk
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:63
 [6] run_work_thunk
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\process_messages.jl:72
 [7] #96
   @ .\task.jl:406

...and 3 more exceptions.

Stacktrace:
 [1] sync_end(c::Channel{Any})
   @ Base .\task.jl:364
 [2] macro expansion
   @ .\task.jl:383 [inlined]
 [3] _require_callback(mod::Base.PkgId)
   @ Distributed C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\Distributed.jl:76
 [4] #invokelatest#2
   @ .\essentials.jl:707 [inlined]
 [5] invokelatest
   @ .\essentials.jl:706 [inlined]
 [6] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:916
 [7] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:897
 [8] top-level scope
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Distributed\src\macros.jl:204
```

**Comment by MilesCranmer** [comment]
Does this issue go away the second time you open up Julia, and don't write the `Pkg` stuff?

**Comment by sheevy** [comment]
No, still getting the same error. What's in your environment, maybe I need to have a package I'm currently missing.
```
(Test2) pkg> st
Project Test2 v0.1.0
Status `C:\Users\siwy\Downloads\julia-b84990e1ac\bin\Test2\Project.toml`
  [8254be44] SymbolicRegression v0.1.0 `https://github.com/MilesCranmer/SymbolicRegression.jl.git#master`
```
```
julia> versioninfo()
Julia Version 1.6.0-beta1.0
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
```

**Comment by MilesCranmer** [comment]
Very strange, I will think more about this. Can you try installing a different Julia packages from GitHub?

The required packages are listed here: https://github.com/MilesCranmer/SymbolicRegression.jl/blob/master/Project.toml

And all installed packages in my env are given here:
https://github.com/MilesCranmer/SymbolicRegression.jl/blob/master/Manifest.toml

**Comment by luckywood** [comment]
I have the same probblem:
Pkg.add(url="https://github.com/MilesCranmer/SymbolicRegression.jl.git")
   Updating git-repo `https://github.com/MilesCranmer/SymbolicRegression.jl.git`
   Updating registry at `~/.julia/registries/General`
######################################################################## 100,0%
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Distributions [31c24e10]:
 Distributions [31c24e10] log:
├─possible versions are: [0.16.0-0.16.4, 0.17.0, 0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.6, 0.23.0-0.23.12, 0.24.0-0.24.10] or uninstalled
 ├─restricted by compatibility requirements with StatsPlots [f3b207a7] to versions: [0.16.0-0.16.4, 0.17.0, 0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.6, 0.23.0-0.23.12, 0.24.0-0.24.10]
 │ └─StatsPlots [f3b207a7] log:
 │   ├─possible versions are: [0.10.0-0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.14.0-0.14.17] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [0.10.0-0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.14.0-0.14.17]
 ├─restricted by compatibility requirements with BlackBoxOptim [a134a8b2] to versions: [0.16.0-0.16.4, 0.17.0, 0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.6, 0.23.0-0.23.12]
 │ └─BlackBoxOptim [a134a8b2] log:
 │   ├─possible versions are: [0.4.0, 0.5.0] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [0.4.0, 0.5.0]
 └─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: 0.24.4-0.24.10 or uninstalled — no versions left
   └─SpecialFunctions [276daf66] log:
     ├─possible versions are: [0.7.0-0.7.2, 0.8.0, 0.9.0, 0.10.0-0.10.3, 1.0.0, 1.1.0, 1.2.0-1.2.1] or uninstalled
     └─restricted to versions 1.1.0-1 by SymbolicRegression [8254be44], leaving only versions [1.1.0, 1.2.0-1.2.1]
       └─SymbolicRegression [8254be44] log:
         ├─possible versions are: 0.1.0 or uninstalled
         └─SymbolicRegression [8254be44] is fixed to version 0.1.0

**Comment by sheevy** [comment]
Tried it on different julia versions, but with no luck:
1.2: Doesn't install due to unsatisfied dependency on SpecialFunctions
1.3, 1.4, 1.5, 1.6-beta: Same error as before.

**Comment by MilesCranmer** [comment]
Hm, it seems like I was too strict with the `[compat]` requirements ([here](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/e446df8dcf69b21cbc09c4b831294e5c9989f73e/Project.toml#L13)), and this is what's creating the installation difficulty.  I don't actually use many of the functions from each required packages so I can probably weaken the version requirements a lot.

Sorry for the installation difficulty, will try to fix this tomorrow.

**Comment by MilesCranmer** [comment]
I updated the [compat] requirements; can you try again?

**Comment by luckywood** [comment]
yes, now it works.  Thanks !

**Comment by sheevy** [comment]
It also works in Test2 environment as long as SymbolicRegression is also installed in the main environment.

**Comment by MilesCranmer** [comment]
Awesome!

**Comment by sheevy** [comment]
Isn't it weird though? I'm not a Julia expert, but shouldn't it work just fine without a need to adding it to the main env?

**Comment by MilesCranmer** [comment]
Yeah, this is definitely weird. Let's try again once it's on the general registry, for now, your added instructions are good - thanks.
