### ISSUE TITLE
[Feature] User defined constants?

### ISSUE THREAD

**Issue by Remotion** [MilesCranmer/SymbolicRegression.jl#103]
It would be very convenient if user defined/provided constants (pi, e, omega, sqrt(2) ...) would be supported.  

How difficult it would be to add this feature?

**Comment by MilesCranmer** [comment]
It searches for arbitrary scalar constants, so in theory, it could already find these.

However, I am assuming you wish to find equations that do not allow arbitrary real numbers(?). This is not built in, but it is really easy to add yourself.

Basically, you want to first disallow real constants in discovered expressions. Then, you could simply input your above constants as **additional columns** in your input data matrix to `EquationSearch`, and it should work.

To add an option that disallows real constants, one could add another piece of code in the `check_constraints` function here:
https://github.com/MilesCranmer/SymbolicRegression.jl/blob/64599a3d6848f4edb153744977130d54f88c95eb/src/CheckConstraints.jl#L136-L159

You could simply run:
```julia
if count_constants(tree) > 0
    return false
end
```
and it should already work.

**Comment by MilesCranmer** [comment]
Btw, you need to also add:
```julia
import ..EquationUtilsModule: count_nodes, count_constants
```
to line 4, so you can use that function.

**Comment by MilesCranmer** [comment]
FYI v0.9.2 includes custom complexities. You can set, e.g., `complexity_of_constants=100` to prevent the use of real constants, and then include whatever constants you like as additional features (and, since `complexity_of_variables=1` by default, those will be favored).

**Comment by Remotion** [comment]
Thanks!  
I will need to look at this.
