### ISSUE TITLE
[Feature] Use NaNMath instead of `abs`

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/SymbolicRegression.jl#109]
Operators should be default use NaNMath https://github.com/mlubin/NaNMath.jl, instead of my versions which simply map input to the valid domain like `log(abs(x))`. Since the evaluator already detects NaNs by default, this should work well and expressions will automatically try to avoid having improper inputs.

**Comment by johanbluecreek** [comment]
I can take a look at this. I'm not too familiar with the whole code base yet, but right now it seems to more or less to trace the use of the operations defined in `src/Operators.jl` and replace the occurrences with `NaNMath.log` and so on. If you have any other thoughts on the approach before I start let me know.

I also wanted to ask, I just did a quick naive benchmark on `NaNMath` versus an own implementation and `NaNMath` seems to perform consistently a bit worse,

```julia
julia> using NaNMath

julia> function log_nan(x)
           x < 0.0 && return NaN
           return log(x)
       end
log_nan (generic function with 1 method)

julia> X = rand(50_000_000) .* 2 .- 1;

julia> @time NaNMath.log.(X);
  0.661889 seconds (132.60 k allocations: 388.716 MiB, 0.80% gc time, 6.57% compilation time)

julia> @time NaNMath.log.(X);
  0.685413 seconds (4 allocations: 381.470 MiB)

julia> @time NaNMath.log.(X);
  0.614610 seconds (4 allocations: 381.470 MiB)

julia> @time log_nan.(X);
  0.644774 seconds (117.23 k allocations: 387.860 MiB, 12.58% gc time, 11.42% compilation time)

julia> @time log_nan.(X);
  0.543851 seconds (4 allocations: 381.470 MiB)

julia> @time log_nan.(X);
  0.477451 seconds (4 allocations: 381.470 MiB, 3.61% gc time)
```

Comparing the two best times above, `NaNMath` performs some 29% slower. Maybe this is not something significant enough (or maybe I'm too naive in trusting this benchmark), and maybe it is easier to just go with `NaNMath` anyway, I just wanted to ask it that is still the desired solution.

**Comment by MilesCranmer** [comment]
Also, after defining new operators with custom names like `log_nan`, you could map their function name to simply `log` when printed, by modifying https://github.com/MilesCranmer/SymbolicRegression.jl/blob/29f6bf19d0920f74fb79431418d3e34ea2c4af75/src/Equation.jl#L204

**Comment by MilesCranmer** [comment]
This was completed with #123 . (Thanks again!)
