### ISSUE TITLE
express a number as a function of given constants

### ISSUE THREAD

**Issue by qwertyjl** [MilesCranmer/SymbolicRegression.jl#127]
Is it possible to use SymbolicRegression to express a number as a function of given constants?
If I have a number (2.221441469079) and a vector ([2.0, π, ℯ]), can I get a function built with the constants given in the vector that best approximates the number? (in this case π/√2)
Another example is: expressing physical constants in terms of other physical constants, discovering new equations.
@ChrisRackauckas

**Comment by MilesCranmer** [comment]
One thing you could do is pass your constants as additional features in `X`, and then weight the complexity of regular constants to be prohibitively expensive (i.e., `Options(complexity_of_constants=100)`).

**Comment by MilesCranmer** [comment]
For example:
```julia
options = Options(
    complexity_of_constants=100, 
    unary_operators=(sqrt,), 
    binary_operators=(+, *, /, -), 
    mutationWeights=[0.0, 0.47, 0.79, 5.1, 1.7, 0.0020, 0.00023, 0.21],
    # ^ Set p(mutate_constant)=0.0
    shouldOptimizeConstants=false
    # ^ Set constant optimization off
)
X = ones(Float64, 3, 1)
X[1] = 2
X[2] = pi
X[3] = exp(1)
y = [2.221441469079]
EquationSearch(X, y; options=options, multithreading=true, varMap=["2", "pi", "e"], niterations=100)
```
Although I'm not sure why it stops optimizing in this case... very strange. Granted I haven't really tested searches without constants before.

**Comment by MilesCranmer** [comment]
Okay I think I know why it's not working. It's something to do with the fact that the average of `y`, which is normally the **baseline loss**, here, is actually a solution with zero error.

You can trick the search into treating this as a normal expression search by doing the following:

```julia
X = ones(Float64, 4, 10);
X[1, :] .= LinRange(1, 10, 10);
X[2, :] .= 2.0;
X[3, :] .= pi;
X[4, :] .= exp(1);
y = X[1, :] .* 2.221441469079
```
So, in this case, the true solution will be `y = x * 2.221441469079`. So the baseline solution, equal to the average of x, will be bad.

Set up the options as before:
```julia
options = Options(
    complexity_of_constants=100, 
    unary_operators=(sqrt,), 
    binary_operators=(+, *, /, -), 
    mutationWeights=[0.0, 0.47, 0.79, 5.1, 1.7, 0.0020, 0.00023, 0.21],
    # ^ Set p(mutate_constant)=0.0
    shouldOptimizeConstants=false
    # ^ Set constant optimization off
)
```
And search with an additional variable specified in the `varMap`:
```julia
EquationSearch(X, y; options=options, multithreading=true, varMap=["x", "2", "pi", "e"], niterations=1000)
```
Now, it actually seems to find it correctly. Here's my printout:
```
Started!
24.5%┣████████████████████████████████████████▊                                                                                                                             ┫ 3679/15000 [00:27<01:23, 135.9 it/s]Head worker occupation: 17.0%                                                                                                                                                                                     Press 'q' and then <enter> to stop execution early.                                                                                                                                                               Hall of Fame:                                                                                                                                                                                                     -----------------------------------------                                                                                                                                                                         Complexity  Loss       Score     Equation                                                                                                                                                                         1           5.744e+01  -3.442e-01  x                                                                                                                                                                              3           1.888e+00  1.708e+00  (x + x)                                                                                                                                                                         5           2.455e-01  1.020e+00  ((x * pi) - x)                                                                                                                                                                  6           1.287e-24  2.303e+01  ((x * pi) / sqrt(2))                                                                                                                                                            11          1.284e-24  5.252e-04  ((((x * pi) + 2) / sqrt(2)) - sqrt(2))
```

which, as you can see, contains `x * pi / sqrt(2)`. Divide out the `x`, and you've got your expression!

**Comment by MilesCranmer** [comment]
I am pretty sure this is why it wasn't working otherwise:
https://github.com/MilesCranmer/SymbolicRegression.jl/blob/29f6bf19d0920f74fb79431418d3e34ea2c4af75/src/LossFunctions.jl#L56

So since the baseline loss is zero, every expression was getting an infinite loss. Let me fix that...

**Comment by MilesCranmer** [comment]
Okay, with this fix on master: https://github.com/MilesCranmer/SymbolicRegression.jl/commit/85f4909e8156ba8ff6cf89122371901a13df5688, the first code snippet I sent you now works! So no need for the workaround.

Cheers,
Miles
