### ISSUE TITLE
How to fix a number of variables in predicted equations

### ISSUE THREAD

**Issue by MrBenzWorld** [MilesCranmer/SymbolicRegression.jl#130]
Could you tell me, How to fix a number of variables in predicted equations?  For example, I'm giving 5 variables as input, I need an equation with these 5 variables. 
At present, I'm getting a number of equations, which is good, but not with all variables. 
Thank you.

You have provided a detailed example in Python, Please provide a detailed example in Julia also.
Thank you

**Comment by MilesCranmer** [comment]
Hi @MrBenzWorld,

I think this post has the same question: https://github.com/MilesCranmer/PySR/issues/44. Basically, you can't (by default). You could try to program this yourself, though, by modifying the function `eval_loss` to punish an expression for not using one of the five variables.

The Julia example is shown here: https://github.com/MilesCranmer/SymbolicRegression.jl#quickstart - many of the options are the same as in PySRRegressor, although sometimes they have different names.

Best,
Miles
