### ISSUE TITLE
Typo in `grad_deg2_eval` return on complete check

### ISSUE THREAD

**Issue by djmoore26** [MilesCranmer/SymbolicRegression.jl#131]
Reading through some of the code, I noticed a typo in this block:
https://github.com/MilesCranmer/SymbolicRegression.jl/blob/90830eb421f7af50203e6a425a1ee66b3e44429b/src/EvaluateEquationDerivative.jl#L257-L264

Maybe I am misunderstanding something, but it looks to me like L264 should be
```
@return_on_false2 complete2 cumulator2 dcumulator2
```
instead of returning `cumulator1 dcumulator1`

**Comment by djmoore26** [comment]
Actually, looking more closely, this does not seem like a typo. If the right evaluation failed, don't accumulate its (incomplete) results. I will wait for someone else to review, but this can be closed

**Comment by MilesCranmer** [comment]
Hi @djmoore26,
Indeed this appears to be a typo, thanks for pointing it out!
However, in actuality, it will not affect the evaluation though - the `return_on_check` macro returns *any* array when evaluation fails. Just so the function is type stable, and so I don’t have extra allocations, I usually return the previously-allocated array. But I could return an array of NaNs or anything else - the array shouldn’t be used, as the completion flag will be set to false. 
cheers,
Miles

**Comment by djmoore26** [comment]
Thanks for comfirming!
