### ISSUE TITLE
bigfloat doesn't work

### ISSUE THREAD

**Issue by qwertyjl** [MilesCranmer/SymbolicRegression.jl#134]
If I try to use bigfloat variables I get an error: 
`ERROR: MethodError: no method matching randn(::Random.TaskLocalRNG, ::Type{BigFloat})`

OT question: Can I use SymbolicRegression to generate random math functions?

**Comment by MilesCranmer** [comment]
Hi @qwertyjl,

Run this code to add the `randn` method for BigFloats and it will work:
```julia
using Random: AbstractRNG

try
    # In case randn(BigFloat) gets defined in the future
    randn(BigFloat)
catch e
    if isa(e, MethodError)
        Base.randn(::Type{BigFloat}, args::Integer...) = BigFloat.(randn(Float64, args...))
        Base.randn(rng::AbstractRNG, ::Type{BigFloat}, args::Integer...) = BigFloat.(randn(rng, Float64, args...))
    else
        throw(e)
    end
end
```
(I experienced the same issue here: https://github.com/JuliaLang/julia/issues/27858#issuecomment-1232264692 - apparently this will be added in Julia 1.9)

**Comment by MilesCranmer** [comment]
By the way - I'd be happy to accept a PR putting this code directly into SymbolicRegression.jl, if you'd be interested!

(Maybe a new `Extensions.jl` file - which could be included by the main `SymbolicRegression.jl` file.)
