### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by owiecc** [MilesCranmer/SymbolicRegression.jl#14]
Even with `verbosity=0` there is still a lot of messages printed, e.g.:
```julia
function activate_env_on_workers(procs, project_path::String)
    println("Activating environment on workers.")
    ...
end
```
I think all the offending lines are in the `Utils.jl` file.

**Comment by MilesCranmer** [comment]
Thanks; good point! Let me fix this right away.

**Comment by MilesCranmer** [comment]
Pushed to master. verbosity=0 turns off all printing. I still see the "Activating environment at ..." when activating the environment on workers, due to Pkg.activate() running - is that okay to leave as is?

**Comment by MilesCranmer** [comment]
(it appears `Pkg.activate()` doesn't have a quite mode)

**Comment by MilesCranmer** [comment]
Added in v0.5.0.
