### ISSUE TITLE
AssertionError: isfinite(phi_c) && isfinite(dphi_c)

### ISSUE THREAD

**Issue by MilesCranmer** [MilesCranmer/SymbolicRegression.jl#17]
Sometimes I see this issue during the step "Testing entire pipeline on workers", even without BFGS turned on. It appears this happens during Newton's method. I have only observed this with very nonlinear operators like power laws and exponential functions.

To fix this issue for BFGS, I changed from HagerZhang (default) to BackTracking for the line search. I suppose we should try this for the other optimization strategies as well?

Another thing I should note is that this error goes away with increasing the precision, so it seems it just encounters an error during optimization.

**Comment by PhilippThoelke** [comment]
I'm encountering this error very consistently when using the following parameters (in the Python frontend)
```python
pysr(x, y, weights=weights, procs=10, populations=10, annealing=False, useFrequency=True, progress=True,
optimizer_algorithm='BFGS', optimizer_iterations=10, optimize_probability=1,
unary_operators=['neg', 'exp', 'sin'], binary_operators=['+', '-', '*', '/', 'pow'])
```
I have installed the latest version of this package (v0.5.16) and if I understand it correctly, this version already uses BackTracking for the line search.
