### ISSUE TITLE
[Feature]: MLJ integration

### ISSUE THREAD

**Issue by ericphanson** [MilesCranmer/SymbolicRegression.jl#225]
### Feature Request

I think it could be really cool to have an [MLJ](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/) integration for SymbolicRegression. As an example of how it could be used, in https://discourse.julialang.org/t/ann-sirus-jl-v1-2-interpretable-machine-learning-via-rule-extraction/100932/2 I compared SymbolicRegression to [SIRUS](https://github.com/rikhuijzer/SIRUS.jl) for performing interpretable regression on a basic ML example dataset (Boston housing).

**Comment by MilesCranmer** [comment]
Sure, sounds like a great idea! What methods do we need to write to interface it? And I guess it would go in `ext/`?

**Comment by MilesCranmer** [comment]
Potentially fixed by #226

**Comment by ablaom** [comment]
Generally, only MLJModelInterface.jl is needed and it is very light. I think making it a hard dependency should be fine.
