### ISSUE TITLE
[Feature]: ternary operators 

### ISSUE THREAD

**Issue by ericphanson** [MilesCranmer/SymbolicRegression.jl#227]
### Feature Request

This might not be feasible, but I think it would be interesting to be able to model piecewise functions. I think this would basically need something like `choice(x, y, z) = ifelse(x > 0, y, z)`.

**Comment by ericphanson** [comment]
Actually thinking a bit more, this could be expressed as `(x > 0)*y + (x <= 0)*z` so I don’t think ternary operators are strictly necessary.

**Comment by MilesCranmer** [comment]
Also see https://github.com/MilesCranmer/SymbolicRegression.jl/issues/102 but yeah I agree with you – generally it's surprisingly rare to need an operator that can't be expressed as a binary operator. Though it could be true that `ifelse(x, y, z)` may be more simple for some expressions than stacking binary operators like `(>=)(x, y)` and `(*)`.

The only true ternary operators – which are not reducible – I've run into are weird basis functions used to solve some PDEs, where the operator has multiple parameters.

If needed we would first need to generalize https://github.com/SymbolicML/DynamicExpressions.jl/

**Comment by MilesCranmer** [comment]
There's actually very few functions that need to be rewritten in the core type: https://github.com/SymbolicML/DynamicExpressions.jl/blob/6be88b78dca76013086f29f2ff22f6a532d20460/src/base.jl#L68-L136.

Though there are some other mutation functions in SymbolicRegression.jl that would need to re-weight their mutation probabilities based on the max degree.
