### ISSUE TITLE
How can I set the maximum number of nests?

### ISSUE THREAD

**Issue by Shota123-pixel** [MilesCranmer/SymbolicRegression.jl#285]
### Feature Request

I would like to set the maximum number of nests in sin and cos.
In your paper, users can set the maximum number of nests. However, I can not find how to change it...
Therefore, I would appreciate it if you could tell me how to set the maximum number of nests.

**Comment by MilesCranmer** [comment]
You can use the `nested_constraints` parameter

**Comment by Shota123-pixel** [comment]
Thank you very much for your quick reply!! I will try it!!
Also, I want to set a loss function to add constraints for recurrence and frequency. In your paper, you use C(E):"frecency" to estimate simple expressions. Is there any option to set C(E) by default?

**Comment by MilesCranmer** [comment]
Glad I could help!

Oh frecency is turned on by default

**Comment by Shota123-pixel** [comment]
Thank you very much for your kind reply!!
Thanks to you, I can use effectively Symbolic Regression.jl!!
