### ISSUE TITLE
[Feature]: Training on high dimensions X 

### ISSUE THREAD

**Issue by qizzhao** [MilesCranmer/SymbolicRegression.jl#299]
### Feature Request

I have seen many posts that tutorial about training on 2dimensional's X or 1dimensional's X. And I am going to make a symbolic regression model, which input X is 3-dimenstion and input y is 2-dimension. Could SymbolicRegression.jl handle this? If yes, how to do it. (Please give me a short example please). Thank you.

**Comment by MilesCranmer** [comment]
Let's move to https://github.com/MilesCranmer/PySR/discussions/584
