### ISSUE TITLE
[BUG]: frozen REPL in VSCode

### ISSUE THREAD

**Issue by rafaelcuperman** [MilesCranmer/SymbolicRegression.jl#370]
### What happened?

All the details can be found here:
https://discourse.julialang.org/t/symbolicregression-jl-freezing-my-terminal-when-running-report/119368/2

In summary, when using SymbolicRegression.jl in VS Code in windows, after running `fit!(match)` the REPL freezes and I can't type any more. It is non-responsive. 
I have been working with a local fork of the package modifying a line as recommended here: https://discourse.julialang.org/t/symbolicregression-jl-freezing-my-terminal-when-running-report/119368/5?u=elcup

### Version

v1.0.1

### Operating System

Windows

### Interface

Other (specify below)

### Extra Info

Working on VS Code in Windows

**Comment by MilesCranmer** [comment]
The workaround for this issue is to apply the change

```diff
- stdin_reader = watch_stream(stdin)
+ stdin_reader = watch_stream(devnull)
```
to src/SymbolicRegression.jl.

Its something about watching stdin that causes the Julia VSCode integration to hang. Maybe also worth cross-reporting the issue to the VSCode extension for Julia?
