### ISSUE TITLE
Version of SymbolicUtils.jl blocked to 0.13 while the current version is 0.16

### ISSUE THREAD

**Issue by hurak** [MilesCranmer/SymbolicRegression.jl#46]
Installing `SymbolicRegression.jl` force downgrade of `ModelingToolkit.jl`, `Symbolics.jl` and `SymbolicUtils.jl`. I can read in `Project.toml` the compat entry `SymbolicUtils = "0.13"`. If I understand the convention described in [https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0](https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0) correctly, this binds the package to `0.13.x` versions. Is that necessary here? `SymbolicUtils.jl` is now in version `0.16.0`.

**Comment by MilesCranmer** [comment]
See https://github.com/MilesCranmer/SymbolicRegression.jl/pull/45. Upgrading SymbolicUtils currently breaks the test suite, so will need to figure out why before adding the updated version.

**Comment by MilesCranmer** [comment]
Actually, it looks like the tests pass. So it’s probably not necessary! But for stability reasons I need to still read the change logs before merging.

**Comment by AlCap23** [comment]
#50 Seems fine on my machine.

**Comment by MilesCranmer** [comment]
Version 0.6.15 should be up soon which satisfies this. Sorry for the delay.
