### ISSUE TITLE
Can't define options as listed in Tutorial, causes Method Error.

### ISSUE THREAD

**Issue by johnabs** [MilesCranmer/SymbolicRegression.jl#54]
I have no idea what's causing this to be honest. I load up Julia 1.6.3, have added SymbolicRegression, and tried defining the options variable as listed on the github page and in the docs, and get the following error. 

```
ERROR: MethodError: no method matching var"#Options#5"(::Tuple{typeof(+), typeof(*), typeof(/), typeof(-)}, ::typeof(exp), ::Nothing, ::L2DistLoss, ::Int64, ::Int64, ::Float32, ::Float32, ::Int64, ::Nothing, ::Bool, ::Bool, ::Bool, ::Float32, ::Bool, ::Nothing, ::Int64, ::Float32, ::Bool, ::Bool, ::Int64, ::Vector{Float64}, ::Float32, ::Bool, ::Int64, ::Int64, ::Float32, ::Int64, ::Float32, ::Nothing, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Nothing, ::String, ::Int64, ::Float32, ::Int64, ::Nothing, ::Nothing, ::String, ::Float64, ::Type{Options})
Closest candidates are:
  var"#Options#5"(::Tuple{Vararg{Any, nbin}}, ::Tuple{Vararg{Any, nuna}}, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Type{Options}) where {nuna, nbin} at /home/johnbs/.julia/packages/SymbolicRegression/dhfuI/src/Options.jl:261
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

The code I'm using is as follows, and this happens even when the only package I have loaded is this one and its dependencies. Any help would be greatly appreciated.
```
options = SymbolicRegression.Options(
    binary_operators=(+, *, /, -),
    unary_operators=(exp),
    npopulations=20
);
```

**Comment by johnabs** [comment]
Okay, update, apparently the unary_operators tuple has to contain more than one value? If I define it as (exp,exp) it works but (exp) fails.

**Comment by MilesCranmer** [comment]
Oh, this is because `(exp)` is not a tuple - it just simplifies to `exp`. You need to write `(exp,)` to have it be defined as a tuple. Sorry for the confusion.

Cheers,
Miles

**Comment by johnabs** [comment]
Thanks for the clarification! I'll keep that in mind. I have a few questions about the behavior of the optimizer; should I open a new "issue" or just ask here?

**Comment by MilesCranmer** [comment]
Up to you! If it's a completely different issue, it might help others searching for help to have it separated as a separate issue.
