### ISSUE TITLE
Mangled name from @FromFile displayed in docs

### ISSUE THREAD

**Issue by frankier** [MilesCranmer/SymbolicRegression.jl#78]
I am posting this here since I am encountering the same issue myself. Here are the issues in FromFile.jl and Documenter.jl

https://github.com/Roger-luo/FromFile.jl/issues/41
https://github.com/JuliaDocs/Documenter.jl/issues/1781

**Comment by frankier** [comment]
e.g. https://astroautomata.com/SymbolicRegression.jl/stable/types/

**Comment by MilesCranmer** [comment]
Thanks for posting this issue! I will follow the Documenter.jl thread.

**Comment by MilesCranmer** [comment]
This is fixed now. I ported the package to a manual `module {Name} ... end` system which is functionally equivalent to FromFile, but without the macro. So the docs are no longer mangled now.
