### ISSUE TITLE
Interactive regression / printing epochs

### ISSUE THREAD

**Issue by anicusan** [MilesCranmer/SymbolicRegression.jl#80]
Hello, and thanks for developing this library - I found very good uses for it in my research (granular and fluid dynamics). I noticed that in version 0.8 you introduced an interactive display of equation evolution as the regression progresses that refreshes the terminal screen. While nice on local, interactive workflows, the previous scheme printing each epoch was much more useful on batch jobs on e.g. SLURM clusters where stdout is collected into a file as the job runs; at the moment, the characters printed by the interactive display make the batch outputs incomprehensible, and I had to revert back to v0.7.14.

Would it be possible to have an option to use non-interactive display of equations as the regression progresses, similar to the previous library version?

**Comment by MilesCranmer** [comment]
Yes, you can revert back to the previous printout with the setting `progress=False`. I definitely agree that version is more useful for recording the output over time.

**Comment by anicusan** [comment]
Ah, I see the setting in the docs now, apologies for missing it! Thanks for the quick response, I will close this issue now - good luck with your work! :)
