### ISSUE TITLE
SymbolicUtils Upper Bound

### ISSUE THREAD

**Issue by ChrisRackauckas** [MilesCranmer/SymbolicRegression.jl#82]
This upper bound https://github.com/MilesCranmer/SymbolicRegression.jl/pull/63 is causing some issues using SymbolicRegression.jl, which is then blocking updates in DataDrivenDiffEq.jl. @shashi can you help figure out what's needed here? I think SymbolicRegression.jl was pulling into some SymbolicUtils.jl internals.

**Comment by shashi** [comment]
Through which package does DDD depend on SymbolicRegression?

I have already done a round of updates on this, https://github.com/MilesCranmer/SymbolicRegression.jl/pull/60 https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/428 https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/340 . Very happy to do anything else needed here!

**Comment by ChrisRackauckas** [comment]
It's a direct dependency. 

https://github.com/SciML/DataDrivenDiffEq.jl/blob/master/Project.toml#L25

@AlCap23 do you know the reason for the upper bound here?

But anyways, for v0.19, it seems there's an issue with `has_trig` missing. https://github.com/MilesCranmer/SymbolicRegression.jl/runs/4959859026?check_suite_focus=true#step:6:190

**Comment by shashi** [comment]
Ah okay. has_trig is not part of the API...

**Comment by ChrisRackauckas** [comment]
What should it be updated to?

**Comment by shashi** [comment]
I would recommend just copy pasting the function here.

**Comment by shashi** [comment]
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/src/utils.jl#L37-L47

**Comment by MilesCranmer** [comment]
Fixed on v0.9.0+
