### ISSUE TITLE
Update SymbolicUtils

### ISSUE THREAD

**Issue by jackisdesigning** [MilesCranmer/SymbolicRegression.jl#98]
Please consider updating the compatibility requirement for the `SymbolicUtils` package, to v0.19, given the current one is really out of date.

**Comment by MilesCranmer** [comment]
See https://github.com/MilesCranmer/SymbolicRegression.jl/pull/84, https://github.com/MilesCranmer/SymbolicRegression.jl/issues/82, https://github.com/MilesCranmer/SymbolicRegression.jl/issues/59.

Will get to this eventually if others can't get this working.

**Comment by MilesCranmer** [comment]
Closing - please move discussion to #82.

**Comment by MilesCranmer** [comment]
Btw, you can also use SymbolicRegression < 0.7.0, which has the updated SymbolicUtils, although note that there is a simplification bug that will slow things down a bit. But it will work.

**Comment by MilesCranmer** [comment]
Fixed on v0.9.0+ - you can now have an up-to-date SymbolicUtils with the latest SymbolicRegression.
